# Generated by Django 4.2.16 on 2024-11-22 19:00

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-rating', '-date']},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='requirements',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('upcoming', 'Upcoming')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
