# Generated by Django 4.2.16 on 2024-11-22 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_options_remove_deal_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='requirements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='restaurant_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('upcoming', 'Upcoming')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='deals.deal')),
            ],
        ),
    ]
