# Generated by Django 4.2.16 on 2024-11-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_options_remove_deal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
