# Generated by Django 4.2.16 on 2024-12-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_recurrence_days_alter_deal_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
