# Generated by Django 4.2.16 on 2024-12-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_alter_deal_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
